# -*- coding: utf-8 -*-
"""Graficas.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A2MeJ78Gc98zXVRLoKSNcd7nf4KP66RY
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Data_Main = pd.read_excel("ChartData.xlsx")
print(Data_Main)



first_criteria = Data_Main[["Date","Volume"]]
first_graph = first_criteria.plot.bar(x="Date", y="Volume", rot=0)
plt.xlabel("DATE")
plt.ylabel("VOLUME")
plt.title(" VOLUMEN IN TIME")
plt.show()

xs=Main_Data["Date"]
ys=Main_Data["Open"]
plt.xlabel("DATE")
plt.ylabel("PRICE")
plt.title(" OPEN PRICE IN TIME")
plt.plot(xs,ys)